package com.amorif.entities;

/**
 * @author osailton
 */

public enum RoleEnum {
	
	ROLE_AVAL,
	ROLE_SERV,
	ROLE_ALUNO,
	ROLE_BIBLIOTECARIO,
	ROLE_APOIO_ACADEMICO,
	ROLE_SISTEMA,
	ROLE_DOCENTE,
	ROLE_ASSESSORIA_PEDAGOGICA,
	ROLE_COEXPEIN,
	ROLE_COORDENADOR_CURSO,
	ROLE_ASSISTENCIA_ESTUDANTIL,
	ROLE_ASSESSORIA_LABORATORIO,
	ROLE_ADMINISTRADOR

}
