security:
  jwt:
    token:
      secret-key: ${JWT_SECRET_KEY}
      expire-lenght: 3600000
spring:
  profiles:
    active: test
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL_DEV}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
          
logging:
  level: 
    '[org.springframework.data.web]': DEBUG
    